import React from "react";
import KeepReading from "./KeepReading";
import { EnhancedPost } from "../../lib/types";

// Minimal mock EnhancedPost type for demo
const mockPosts: EnhancedPost[] = [
	{
		id: 1,
		slug: "mock-article-1",
		title: { rendered: "Mock Article One" },
		excerpt: {
			rendered: "<p>This is a mock excerpt for article one.</p>",
			protected: false,
		},
		author_name: "Jane Doe",
		author_obj: {
			id: 1,
			name: "Jane Doe",
			url: "#",
			description: "",
			link: "#",
			slug: "jane-doe",
			avatar_urls: {},
			meta: [],
		},
		featured_media_obj: {
			id: 1,
			date: "2024-01-01T00:00:00",
			slug: "mock-image-1",
			type: "attachment",
			link: "#",
			title: { rendered: "Mock Image" },
			author: 1,
			caption: { rendered: "" },
			alt_text: "Mock image alt text",
			media_type: "image",
			mime_type: "image/jpeg",
			media_details: {
				width: 800,
				height: 600,
				file: "mock-image.jpg",
				sizes: {},
			},
			source_url: "/logo/logo.svg",
		},
		categories: [1],
		categories_obj: [
			{
				id: 1,
				count: 1,
				description: "",
				link: "#",
				name: "United States",
				slug: "united-states",
				taxonomy: "category",
				parent: 0,
				meta: [],
			},
		],
		link: "/united-states/article/mock-article-1",
		date: "2024-01-01T00:00:00",
		date_gmt: "2024-01-01T00:00:00Z",
		guid: { rendered: "mock-guid-1" },
		modified: "2024-01-01T00:00:00",
		modified_gmt: "2024-01-01T00:00:00Z",
		status: "publish",
		type: "post",
		content: { rendered: "", protected: false },
		author: 1,
		featured_media: 1,
		format: "standard",
		meta: {},
		tags: [],
		class_list: [],
		coauthors: [],
	},
	{
		id: 2,
		slug: "mock-article-2",
		title: { rendered: "Mock Article Two" },
		excerpt: {
			rendered: "<p>This is a mock excerpt for article two.</p>",
			protected: false,
		},
		author_name: "John Smith",
		author_obj: {
			id: 2,
			name: "John Smith",
			url: "#",
			description: "",
			link: "#",
			slug: "john-smith",
			avatar_urls: {},
			meta: [],
		},
		featured_media_obj: null,
		categories: [2],
		categories_obj: [
			{
				id: 2,
				count: 1,
				description: "",
				link: "#",
				name: "World",
				slug: "world",
				taxonomy: "category",
				parent: 0,
				meta: [],
			},
		],
		link: "/world/article/mock-article-2",
		date: "2024-01-02T00:00:00",
		date_gmt: "2024-01-02T00:00:00Z",
		guid: { rendered: "mock-guid-2" },
		modified: "2024-01-02T00:00:00",
		modified_gmt: "2024-01-02T00:00:00Z",
		status: "publish",
		type: "post",
		content: { rendered: "", protected: false },
		author: 2,
		featured_media: 2,
		format: "standard",
		meta: {},
		tags: [],
		class_list: [],
		coauthors: [],
	},
	{
		id: 3,
		slug: "mock-article-3",
		title: { rendered: "Mock Article Three" },
		excerpt: {
			rendered: "<p>This is a mock excerpt for article three.</p>",
			protected: false,
		},
		author_name: "Staff Writer",
		author_obj: {
			id: 3,
			name: "Staff Writer",
			url: "#",
			description: "",
			link: "#",
			slug: "staff-writer",
			avatar_urls: {},
			meta: [],
		},
		featured_media_obj: null,
		categories: [1],
		categories_obj: [
			{
				id: 1,
				count: 1,
				description: "",
				link: "#",
				name: "United States",
				slug: "united-states",
				taxonomy: "category",
				parent: 0,
				meta: [],
			},
		],
		link: "/united-states/article/mock-article-3",
		date: "2024-01-03T00:00:00",
		date_gmt: "2024-01-03T00:00:00Z",
		guid: { rendered: "mock-guid-3" },
		modified: "2024-01-03T00:00:00",
		modified_gmt: "2024-01-03T00:00:00Z",
		status: "publish",
		type: "post",
		content: { rendered: "", protected: false },
		author: 3,
		featured_media: 3,
		format: "standard",
		meta: {},
		tags: [],
		class_list: [],
		coauthors: [],
	},
];

const KeepReadingMockDemo = () => (
	<div style={{ background: "#f8f8f8", padding: 32 }}>
		<KeepReading posts={mockPosts} title="Mock Keep Reading" />
	</div>
);

export default KeepReadingMockDemo;
